// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zobudirnfehkamxgoclg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvYnVkaXJuZmVoa2FteGdvY2xnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTI5MjksImV4cCI6MjA2NTQ4ODkyOX0.mniJp8lq9wNjYkNx9yK6SXSMDFBraZnBbRcJ4-p1J1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);